'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Book.io.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_io_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_io_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_io_logotext() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_io_logotext", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rainbow_gradient_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rainbow_gradient_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rainbow_gradient_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rainbow_gradient_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;StaffDetails&gt;
        '''  &lt;Staff Id = &quot;001&quot;&gt;
        '''    &lt;FirstName&gt;Hugo&lt;/FirstName&gt;
        '''    &lt;Surname&gt;Ferguson&lt;/Surname&gt;
        '''    &lt;Email&gt;hugoferguson@outlook.com&lt;/Email&gt;
        '''    &lt;Password&gt;desu1&lt;/Password&gt;
        '''    &lt;Mobile&gt;0481 060 515&lt;/Mobile&gt;
        '''    &lt;Address&gt;68 Central Springs Road&lt;/Address&gt;
        '''    &lt;City&gt;Daylesford&lt;/City&gt;
        '''    &lt;PostCode&gt;3460&lt;/PostCode&gt;
        '''    &lt;Wage&gt;100000&lt;/Wage&gt;
        '''    &lt;Role&gt;Staff&lt;/Role&gt;
        '''    &lt;StaffImage&gt;hugoferguson.png&lt;/StaffImage&gt;
        '''    &lt;Status&gt;True&lt;/Status&gt;
        '''  &lt;/Staff&gt;
        '''  &lt;Staff Id  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property StaffDetails() As String
            Get
                Return ResourceManager.GetString("StaffDetails", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
